apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: assetledger
  namespace: assetledger
spec:
  rules:
    - host: inventory-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: assetledger
                port:
                  name: http
